
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = '100 50 75 A102010 A191019 A701070 EPSILON EXIT K102010 K191019 K701070 M102010 M191019 M701070 P102010 P191019 P701070 else eo goexpr : A701070expr : K701070expr : EXIT'
    
_lr_action_items = {'A701070':([0,],[2,]),'K701070':([0,],[3,]),'EXIT':([0,],[4,]),'$end':([1,2,3,4,],[0,-1,-2,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> A701070','expr',1,'p_expr_A701070','main.py',6),
  ('expr -> K701070','expr',1,'p_expr_K701070','main.py',10),
  ('expr -> EXIT','expr',1,'p_EXIT','main.py',15),
]
